// <auto-generated />
using FinalFantasy.RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalFantasy.RepositoryEF.Migrations
{
    [DbContext(typeof(MasterContext))]
    partial class MasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Arma", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuntiDanno")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.ToTable("Arma");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Gamer", b =>
                {
                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NickName");

                    b.ToTable("Gamer");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Personaggio", b =>
                {
                    b.Property<string>("Nome")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ArmaNome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.Property<int>("PuntiVita")
                        .HasColumnType("int");

                    b.Property<string>("personnagio_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nome");

                    b.HasIndex("ArmaNome");

                    b.ToTable("Personaggio");

                    b.HasDiscriminator<string>("personnagio_type").HasValue("Personaggio");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Hero", b =>
                {
                    b.HasBaseType("FinalFantasy.Core1.Entities.Personaggio");

                    b.Property<string>("NickNameGamer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PuntiLivello")
                        .HasColumnType("int");

                    b.Property<int>("TipoEroe")
                        .HasColumnType("int");

                    b.HasIndex("NickNameGamer");

                    b.HasDiscriminator().HasValue("hero");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Monster", b =>
                {
                    b.HasBaseType("FinalFantasy.Core1.Entities.Personaggio");

                    b.Property<int>("TipoMostro")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("monster");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Personaggio", b =>
                {
                    b.HasOne("FinalFantasy.Core1.Entities.Arma", "Arma")
                        .WithMany("Personaggi")
                        .HasForeignKey("ArmaNome");

                    b.Navigation("Arma");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Hero", b =>
                {
                    b.HasOne("FinalFantasy.Core1.Entities.Gamer", "Gamer")
                        .WithMany("Heroes")
                        .HasForeignKey("NickNameGamer");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Arma", b =>
                {
                    b.Navigation("Personaggi");
                });

            modelBuilder.Entity("FinalFantasy.Core1.Entities.Gamer", b =>
                {
                    b.Navigation("Heroes");
                });
#pragma warning restore 612, 618
        }
    }
}
